# Generated by Django 2.1.7 on 2019-02-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.CharField(default='signature', max_length=140),
            preserve_default=False,
        ),
    ]
